# Fancy RGB Matrix functionity
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
OLED_DRIVER_ENABLE = yes

LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
AUDIO_ENABLE = no
MIDI_ENABLE = no
NKRO_ENABLE = yes
WPM_ENABLE = yes

# EXTRAFLAGS += -flto
